sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/work
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
  - CCACHE_SIZE=200M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - MAKEJOBS="-j2"
  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
  - BASE_PACKAGES="zlib1g-dev zip git build-essential libtool autotools-dev automake
    pkg-config libevent-dev libssl-dev bsdmainutils curl libboost-all-dev libdb4.8-dev
    libdb4.8++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler
    libqrencode-dev"
  matrix:
  - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" OPT="NO_QT=1" CONF="--without-gui"
  - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" OPT="NO_QT=1" CONF="--without-gui"
  - HOST=i686-w64-mingw32 PACKAGES="g++-mingw-w64-i686 mingw-w64-i686-dev"
  - HOST=x86_64-w64-mingw32 PACKAGES="g++-mingw-w64-x86-64 mingw-w64-x86-64-dev"
  - HOST=x86_64-unknown-linux-gnu PACKAGES=""
  - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
    libz-dev libbz2-dev libtiff-tools python-dev" OSX_SDK=10.11
before_install:
- openssl aes-256-cbc -K $encrypted_0e9cfbb1cb04_key -iv $encrypted_0e9cfbb1cb04_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 199.247.9.210\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- export PWD_KEY=$(pwd)
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./deploy_key root@199.247.9.210 pwd
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")
install:
- sudo add-apt-repository -y ppa:bitcoin/bitcoin
- sudo apt-get update
- travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $BASE_PACKAGES
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
before_script:
- unset CC; unset CXX
- cd $TRAVIS_BUILD_DIR
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
script:
- OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
- |
  timeout 3500 ./build.sh
    # Convert the timeout exit code to 0.
    RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
before_deploy:
# Set up git user name and tag this commit
      - git config --local user.name "rupaya-project"
      - git config --local user.email "dev@rupayacoin.org"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      - "./pre-deploy.sh"
after_success:
  - scp -i $PWD_KEY/deploy_key $TRAVIS_BUILD_DIR/out/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST root@199.247.9.210:/root/rel
#deploy:
#  provider: s3
#  access_key_id: AKIAIKPTCZAG4GFH5EPQ
#  secret_access_key:
#    secure: sNmtJ8YcKrKo+MXYWRDfbSsHlTnGP1DQPMmUmDR/zE89toduGP9A4u4+xEM3jnK1bUj/dBPtF05zeQynKva9CHmD6/+pz5sX14rgXYDPPE0YB0b1qhgCp7TKa77bEU2B50291puR+XhftFvvWiPg0PMWup7ZZYfySmJF6WIU/dwyT0Pw8I+piapNjOT38xzvYp/OGJSltX5K+ME8W6s/sMsWCok4evvZx5zQ+Bh3I1A5q0QyirjM1JCxz06p1jC0BENgqNHGRXaxgXzrUx24lqB/AoOl9qrvtTfiKxfB1lJLMt59RLUnJ4ol4CvIbd7AQBD8lg8aVraUCs5jgqE5Vaccvn+9CNe5BCSDioiNzv7JVu6yLuPkMnwSagvUeItZIEhWqvcP6FpnJAC/J3Gn2LhN8zJWadYAhvicaUUhKEY+vFdc7HncYpqfiJlNWl90FZ73k8hMM3JayDebhjSpQ29KMfYMVUpjnrnpKxCASFz5d4vpxPlOlZFqwAPBnEPInVGi2IoyWR3+2Cfhi7tQNOZ7TgTUFo3Q6eLfl48F92JEMQQPACytBeTrI7Kdtk5FHxSnKAF5E3o2wR72iym9YedfLjQSCISkcqbozzTB9cY5JLSvZUgmD26wXK63ApPf+LHKe5Q0VJCh/daPSD6K22t25FXeSr8lYkAHPsLpew4=
#  bucket: rupaya
#  skip_cleanup: true
#  local_dir:  $TRAVIS_BUILD_DIR/out/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
#  upload-dir: $TRAVIS_JOB_NUMBER
#  acl: public_read
#  on:
#    repo: rupaya-project/rupaya
#    cache_control: "max-age=21600"
#    on:
#      all_branches: true
